# Generated by Django 3.1.4 on 2020-12-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to='', width_field=250),
        ),
    ]
